---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/events
  label: Events
  create: all
  match: "**/*"
- type: directory
  path: content/frequently-asked-questions
  label: Frequently asked questions
  create: all
  match: "**/*"
- type: directory
  path: content/gallery
  label: Gallery
  create: all
  match: "**/*"
- type: directory
  path: content/paintball-center
  label: Paintball center
  create: all
  match: "**/*"
- type: directory
  path: content/paintball-services
  label: Paintball services
  create: all
  match: "**/*"
- type: directory
  path: content/pricing
  label: Pricing
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: content/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
